### ISSUE TITLE
Support for Serilog

### ISSUE THREAD

**Issue by aimenux** [yarseyah/sentinel#25]
Hello Ray, Is there any planning to support serilog logging provider ? Thanks in advance.

**Comment by yarseyah** [comment]
There wasn't but I've noticed that serilog has sinks for Udp that generate either log4net or log4j (used by nLog) formatted messages - but with some minor differences in the XML namespaces of the messages.  I've updated both implementations to parse the message correctly.

In the next release (or take the sources when the PR is closed) you would just need to select log4net or nlog from Sentinel, depending upon which serilog format you used, e.g. below would require **NLOG** because log4j format.

```csharp
var logger = new LoggerConfiguration()
    .WriteTo.Udp("localhost", 9999, AddressFamily.InterNetwork, new Log4jTextFormatter())
    .WriteTo.Console()
    .MinimumLevel.Verbose()
    .CreateLogger();
```

And the following configuration of serilog would require you to select **LOG4NET**:

```csharp
var logger = new LoggerConfiguration()
   .WriteTo.Udp("localhost", 9998, AddressFamily.InterNetwork, new Log4netTextFormatter())
   .WriteTo.Console()
   .MinimumLevel.Verbose()
   .CreateLogger();
```

It should pick up properties and exceptions, the message displayed in description field of Sentinel is as passed from serilog, no specific processing is performed - I'm not sure what serilog can actually do, so suggestions for enhancements welcome.

PS. If you build from sources, specify `STANDALONE_BUILD` as a compilation directive to avoid worrying about the installers.
